# Generated by Django 3.1.6 on 2021-02-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(0, 'to be activate'), (1, 'unstarted'), (2, 'running'), (3, 'closed')], verbose_name='course status'),
        ),
        migrations.AlterField(
            model_name='coursemember',
            name='types',
            field=models.IntegerField(choices=[(0, 'admin'), (1, 'teacher'), (2, 'asistant'), (3, 'student')], verbose_name='Member type'),
        ),
    ]
