# Generated by Django 3.1.6 on 2021-03-08 13:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_auto_20210307_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Is open to all'),
        ),
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 13, 35, 44, 383974), verbose_name='date created up'),
        ),
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
