# Generated by Django 3.1.6 on 2021-03-08 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210308_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 13, 36, 11, 131122), verbose_name='date created up'),
        ),
    ]
