# Generated by Django 3.1.6 on 2021-03-08 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20210308_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 14, 29, 56, 167777, tzinfo=utc), verbose_name='date created up'),
        ),
    ]
