# Generated by Django 3.1.6 on 2021-03-14 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20210314_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 9, 6, 36, 771214, tzinfo=utc), verbose_name='date created up'),
        ),
    ]
