# Generated by Django 3.1.6 on 2021-04-08 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_auto_20210408_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 9, 33, 10, 650608, tzinfo=utc), verbose_name='date created up'),
        ),
    ]
