# Generated by Django 3.1.6 on 2021-04-08 14:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_auto_20210408_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 14, 26, 19, 304885, tzinfo=utc), verbose_name='date created up'),
        ),
    ]
