# Generated by Django 3.1.6 on 2021-03-14 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0011_auto_20210314_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dockerAPI',
            new_name='docker_api',
        ),
        migrations.AlterField(
            model_name='submission',
            name='commit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 9, 6, 36, 785777, tzinfo=utc), verbose_name='date committed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 9, 6, 36, 784983, tzinfo=utc), verbose_name='date to close'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 9, 6, 36, 784961, tzinfo=utc), verbose_name='date created'),
        ),
    ]
