# Generated by Django 3.1.6 on 2021-03-28 02:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0022_auto_20210327_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='user',
            new_name='submitter',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='course',
        ),
        migrations.AlterField(
            model_name='submission',
            name='commit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 2, 26, 10, 690479, tzinfo=utc), verbose_name='date committed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 2, 26, 10, 689696, tzinfo=utc), verbose_name='date to close'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 2, 26, 10, 689657, tzinfo=utc), verbose_name='date created'),
        ),
    ]
