# Generated by Django 3.1.6 on 2021-03-14 07:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20210314_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionfile',
            old_name='file_hash',
            new_name='hash',
        ),
        migrations.RenameField(
            model_name='submissionfile',
            old_name='file_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 7, 27, 34, 830237, tzinfo=utc), verbose_name='date created'),
        ),
    ]
