# Generated by Django 3.1.6 on 2021-03-14 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import files.rfields
import files.utils


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_auto_20210314_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfile',
            name='content_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 13, 25, 58, 808459, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=files.rfields.RestrictedFileField(upload_to=files.utils.UploadToPathAndRename('submission/2021/03/14')),
        ),
    ]
