# Generated by Django 3.1.6 on 2021-04-08 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import files.rfields
import files.utils


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0027_auto_20210408_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerfile',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 9, 33, 10, 663662, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='dockerfile',
            name='file',
            field=files.rfields.RestrictedFileField(max_length=200, upload_to=files.utils.UploadToPathAndRename('dockerfile/2021/04/08')),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 9, 33, 10, 663662, tzinfo=utc), verbose_name='date created'),
        ),
    ]
