# Generated by Django 3.1.6 on 2021-03-18 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_auto_20210318_2131'),
        ('homeworks', '0018_auto_20210318_2131'),
        ('dockers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True, verbose_name='image id')),
                ('port_open', models.IntegerField(null=True, verbose_name='open port')),
                ('dockerfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.dockerfile')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeworks.task')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=64, verbose_name='container id')),
                ('port_local', models.IntegerField(verbose_name='port open in container')),
                ('port_server', models.IntegerField(verbose_name='port allocated on server')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2021, 3, 18, 13, 31, 18, 909620, tzinfo=utc), verbose_name='date created')),
                ('update_date', models.DateTimeField(default=datetime.datetime(2021, 3, 18, 13, 31, 18, 909650, tzinfo=utc), verbose_name='date last update')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dockers.image')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homeworks.submission')),
            ],
        ),
        migrations.DeleteModel(
            name='DockerStatu',
        ),
    ]
