# Generated by Django 3.1.6 on 2021-03-27 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dockers', '0004_auto_20210318_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 13, 49, 47, 164271, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 13, 49, 47, 164308, tzinfo=utc), verbose_name='date last update'),
        ),
    ]
