# Generated by Django 3.1.6 on 2021-04-08 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dockers', '0013_auto_20210408_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 9, 33, 10, 762816, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 9, 33, 10, 762859, tzinfo=utc), verbose_name='date last update'),
        ),
    ]
