# Generated by Django 3.1.6 on 2021-04-09 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dockers', '0016_auto_20210408_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 6, 48, 35, 326383, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 6, 48, 35, 326416, tzinfo=utc), verbose_name='date last update'),
        ),
    ]
