# Generated by Django 3.1.6 on 2021-02-22 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, verbose_name='user name')),
                ('password', models.CharField(max_length=128, verbose_name='maked password')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('signup_date', models.DateTimeField(default=datetime.datetime(2021, 2, 22, 8, 38, 29, 220684), verbose_name='date signed up')),
                ('last_login', models.DateTimeField(default=datetime.datetime(2021, 2, 22, 0, 0), verbose_name='last login')),
                ('token', models.CharField(max_length=128, null=True, verbose_name='login token')),
                ('counter', models.DateTimeField(default=datetime.datetime(2021, 2, 22, 8, 38, 29, 220747), verbose_name='counter (multiple use)')),
                ('privilege', models.IntegerField(choices=[(0, 'admin_public'), (1, 'reserved'), (2, 'reserved'), (3, 'reserved'), (4, 'reserved'), (5, 'normal')], default=5, verbose_name='User Privilege')),
                ('status', models.IntegerField(choices=[(0, 'unactivated'), (1, 'normal'), (2, 'banned'), (3, 'canceled')], default=0, verbose_name='User Status')),
                ('avatar', models.CharField(max_length=128, verbose_name='avatar path')),
                ('realname', models.CharField(max_length=16, verbose_name='real name')),
                ('uid', models.CharField(max_length=32, verbose_name='user(student/teacher) number')),
            ],
            options={
                'verbose_name': 'User information',
                'verbose_name_plural': 'User information',
            },
        ),
    ]
