# Generated by Django 3.1.6 on 2021-03-07 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_auto_20210223_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuxiliary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realname', models.CharField(blank=True, max_length=16, verbose_name='real name')),
                ('uid', models.CharField(blank=True, max_length=32, verbose_name='user(student/teacher) number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User auxiliary information',
                'verbose_name_plural': 'User auxiliary information',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
