# Generated by Django 3.1.6 on 2021-04-06 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_auto_20210307_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauxiliary',
            name='realname',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='real name'),
        ),
        migrations.AlterField(
            model_name='userauxiliary',
            name='uid',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='user(student/teacher) number'),
        ),
        migrations.AlterField(
            model_name='userauxiliary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary', to=settings.AUTH_USER_MODEL),
        ),
    ]
