# Generated by Django 3.1.6 on 2021-03-10 12:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filedocker'),
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(verbose_name='course id')),
                ('user_id', models.IntegerField(verbose_name='user id')),
                ('task_id', models.IntegerField(verbose_name='task id')),
                ('status', models.IntegerField(choices=[(0, '(reserved)'), (1, 'undo&intime'), (2, 'done&intime'), (3, 'undo&timeout'), (4, 'done&timeout')], default=0, verbose_name='status')),
                ('commit_date', models.DateTimeField(verbose_name='date committed')),
                ('answer', models.CharField(max_length=1024, verbose_name='answer')),
                ('score', models.IntegerField(verbose_name='score')),
                ('comment', models.CharField(max_length=1024, verbose_name='comment')),
                ('file_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.filehomework')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('description', models.CharField(max_length=1024, verbose_name='description')),
                ('course_id', models.IntegerField(verbose_name='course id')),
                ('creator_id', models.IntegerField(verbose_name='creater user id')),
                ('tips', models.CharField(blank=True, max_length=1024, verbose_name='tips')),
                ('answer', models.CharField(blank=True, max_length=1024, verbose_name='answer')),
                ('dockerAPI', models.CharField(blank=True, max_length=128, verbose_name='dockerAPI')),
                ('status', models.IntegerField(choices=[(0, 'draft'), (1, 'running'), (2, 'closed')], default=0, verbose_name='homework status')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2021, 3, 10, 12, 1, 7, 623990, tzinfo=utc), verbose_name='date created')),
                ('close_date', models.DateTimeField(default=datetime.datetime(2021, 4, 9, 12, 1, 7, 624011, tzinfo=utc), verbose_name='date to close')),
            ],
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
        migrations.DeleteModel(
            name='HomeworkStatu',
        ),
    ]
