# Generated by Django 3.1.6 on 2021-03-13 12:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210313_2037'),
        ('homeworks', '0005_auto_20210310_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='answer',
        ),
        migrations.AlterField(
            model_name='submission',
            name='comment',
            field=models.CharField(blank=True, max_length=1024, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='commit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 12, 37, 28, 632002, tzinfo=utc), verbose_name='date committed'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='files.filehomework'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(blank=True, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unfinished'), (1, 'Submitted'), (2, 'Commented')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 12, 12, 37, 28, 631171, tzinfo=utc), verbose_name='date to close'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 12, 37, 28, 631103, tzinfo=utc), verbose_name='date created'),
        ),
    ]
