# Generated by Django 3.1.6 on 2021-03-14 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0009_auto_20210313_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='comment',
            field=models.CharField(max_length=1024, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='commit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 7, 16, 3, 336340, tzinfo=utc), verbose_name='date committed'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(null=True, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='task',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 13, 7, 16, 3, 335616, tzinfo=utc), verbose_name='date to close'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 14, 7, 16, 3, 335593, tzinfo=utc), verbose_name='date created'),
        ),
    ]
