# Generated by Django 3.1.6 on 2021-03-16 03:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0013_auto_20210314_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='commit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 3, 43, 56, 535292, tzinfo=utc), verbose_name='date committed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 3, 43, 56, 534502, tzinfo=utc), verbose_name='date to close'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 3, 43, 56, 534479, tzinfo=utc), verbose_name='date created'),
        ),
    ]
