# Generated by Django 3.1.6 on 2021-03-28 08:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0023_auto_20210328_1649'),
        ('homeworks', '0024_auto_20210328_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='commit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 8, 49, 32, 660797, tzinfo=utc), verbose_name='date committed'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='files.submissionfile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 8, 49, 32, 660090, tzinfo=utc), verbose_name='date to close'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 8, 49, 32, 660052, tzinfo=utc), verbose_name='date created'),
        ),
    ]
