# Generated by Django 3.1.6 on 2021-04-06 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0026_auto_20210328_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='commit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 7, 5, 37, 807205, tzinfo=utc), verbose_name='date committed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 7, 5, 37, 806494, tzinfo=utc), verbose_name='date to close'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 7, 5, 37, 806470, tzinfo=utc), verbose_name='date created'),
        ),
    ]
