# Generated by Django 3.1.6 on 2021-04-08 14:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0030_auto_20210408_2226'),
        ('homeworks', '0031_auto_20210408_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='commit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 14, 26, 19, 319325, tzinfo=utc), verbose_name='date committed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 14, 26, 19, 318650, tzinfo=utc), verbose_name='date to close'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 14, 26, 19, 318620, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dockerfile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.dockerfile'),
        ),
    ]
