# Generated by Django 3.1.6 on 2021-04-09 06:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0031_auto_20210409_1448'),
        ('homeworks', '0032_auto_20210408_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auxiliary_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.submissionfile'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='commit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 6, 48, 35, 234089, tzinfo=utc), verbose_name='date committed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 6, 48, 35, 233305, tzinfo=utc), verbose_name='date to close'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 6, 48, 35, 233279, tzinfo=utc), verbose_name='date created'),
        ),
    ]
