# Generated by Django 3.1.6 on 2021-05-09 12:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0032_auto_20210509_2029'),
        ('homeworks', '0033_auto_20210409_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='commit_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 12, 29, 26, 69960, tzinfo=utc), verbose_name='date committed'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='files.submissionfile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 12, 29, 26, 69020, tzinfo=utc), verbose_name='date to close'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 9, 12, 29, 26, 68984, tzinfo=utc), verbose_name='date created'),
        ),
    ]
