# Generated by Django 3.1.4 on 2021-02-11 12:44

from django.db import migrations, models
import files.rfields


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='user id')),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('hid', models.IntegerField(verbose_name='homework id')),
                ('file', files.rfields.RestrictedFileField(upload_to='docker/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
