# Generated by Django 3.1.6 on 2021-03-13 12:37

from django.db import migrations, models
import files.rfields
import files.utils


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_filedocker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileDocker',
        ),
        migrations.DeleteModel(
            name='FileHomeworkStatu',
        ),
        migrations.RemoveField(
            model_name='filehomework',
            name='hid',
        ),
        migrations.RemoveField(
            model_name='filehomework',
            name='uid',
        ),
        migrations.AddField(
            model_name='filehomework',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='filehomework',
            name='file',
            field=files.rfields.RestrictedFileField(upload_to=files.utils.UploadToPathAndRename),
        ),
    ]
