# Generated by Django 3.1.6 on 2021-03-13 13:34

from django.db import migrations, models
import files.rfields
import files.utils


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20210313_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='filehomework',
            name='file_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='filehomework',
            name='file',
            field=files.rfields.RestrictedFileField(upload_to=files.utils.UploadToPathAndRename('Y/%m/%d/')),
        ),
    ]
