# Generated by Django 3.1.6 on 2021-03-13 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import files.rfields
import files.utils


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20210313_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filehomework',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 14, 9, 31, 701497, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='filehomework',
            name='file',
            field=files.rfields.RestrictedFileField(upload_to=files.utils.UploadToPathAndRename('2021/03/13')),
        ),
    ]
