# Generated by Django 3.1.6 on 2021-03-13 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import files.rfields
import files.utils


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_auto_20210313_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=32)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2021, 3, 13, 14, 16, 2, 737558, tzinfo=utc), verbose_name='date created')),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('file', files.rfields.RestrictedFileField(upload_to=files.utils.UploadToPathAndRename('2021/03/13'))),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
