# Generated by Django 3.1.6 on 2021-03-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0009_auto_20210313_2216'),
        ('files', '0006_submissionfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileHomework',
        ),
    ]
