# Generated by Django 3.1.6 on 2021-03-16 08:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_auto_20210316_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 8, 50, 37, 173724, tzinfo=utc), verbose_name='date created'),
        ),
    ]
