# Generated by Django 3.1.6 on 2021-03-17 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import files.rfields
import files.utils


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_auto_20210316_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfile',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 12, 16, 53, 712251, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=files.rfields.RestrictedFileField(upload_to=files.utils.UploadToPathAndRename('submission/2021/03/17')),
        ),
    ]
