# Generated by Django 3.1.6 on 2021-03-18 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import files.rfields
import files.utils


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0015_auto_20210317_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2021, 3, 18, 13, 31, 18, 819658, tzinfo=utc), verbose_name='date created')),
                ('hash', models.CharField(blank=True, max_length=64)),
                ('content_type', models.CharField(blank=True, max_length=64, null=True)),
                ('file', files.rfields.RestrictedFileField(upload_to=files.utils.UploadToPathAndRename('dockerfile/2021/03/18'))),
                ('status', models.IntegerField(choices=[(1, 'To be review'), (2, 'Reviewed'), (3, 'Image built')], default=1, verbose_name='dockerfile review status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 13, 31, 18, 819658, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=files.rfields.RestrictedFileField(upload_to=files.utils.UploadToPathAndRename('submission/2021/03/18')),
        ),
    ]
