# Generated by Django 3.1.6 on 2021-03-13 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20210313_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 12, 35, 11, 686433, tzinfo=utc), verbose_name='date created up'),
        ),
    ]
