# Generated by Django 3.1.6 on 2021-03-13 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20210313_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 12, 37, 28, 544567, tzinfo=utc), verbose_name='date created up'),
        ),
    ]
