# Generated by Django 3.1.6 on 2021-03-16 03:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20210314_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 16, 3, 43, 56, 521209, tzinfo=utc), verbose_name='date created up'),
        ),
    ]
