# Generated by Django 3.1.6 on 2021-03-18 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_auto_20210317_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 13, 31, 21, 444133, tzinfo=utc), verbose_name='date created up'),
        ),
    ]
