# Generated by Django 3.1.6 on 2021-03-28 02:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_auto_20210327_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 2, 26, 10, 671336, tzinfo=utc), verbose_name='date created up'),
        ),
    ]
