# Generated by Django 3.1.6 on 2021-03-28 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_auto_20210328_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 8, 43, 56, 670614, tzinfo=utc), verbose_name='date created up'),
        ),
    ]
