# Generated by Django 3.1.6 on 2021-04-06 07:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_auto_20210328_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 7, 5, 37, 792149, tzinfo=utc), verbose_name='date created up'),
        ),
    ]
