# Generated by Django 3.1.6 on 2021-04-08 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_auto_20210408_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 13, 46, 24, 331448, tzinfo=utc), verbose_name='date created up'),
        ),
    ]
