# Generated by Django 3.1.6 on 2021-04-09 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_auto_20210408_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 6, 48, 35, 218759, tzinfo=utc), verbose_name='date created up'),
        ),
    ]
