# Generated by Django 3.1.4 on 2021-02-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockerStatu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctrid', models.IntegerField(verbose_name='creater user id')),
                ('hid', models.IntegerField(verbose_name='homework id')),
                ('name', models.CharField(max_length=32, verbose_name='tag name')),
                ('ctnid', models.CharField(max_length=64, verbose_name='container id')),
                ('imgid', models.CharField(max_length=64, verbose_name='image id')),
                ('iport', models.IntegerField(verbose_name='port in container')),
                ('oport', models.IntegerField(verbose_name='port in server')),
                ('types', models.IntegerField(verbose_name='types')),
                ('status', models.IntegerField(verbose_name='status')),
                ('create_date', models.DateTimeField(verbose_name='date created')),
                ('update_date', models.DateTimeField(verbose_name='date last update')),
            ],
        ),
    ]
