# Generated by Django 3.1.6 on 2021-03-28 08:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0024_auto_20210328_1643'),
        ('dockers', '0007_auto_20210328_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 8, 43, 56, 771519, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instance', to='homeworks.submission'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 28, 8, 43, 56, 771550, tzinfo=utc), verbose_name='date last update'),
        ),
    ]
