# Generated by Django 3.1.6 on 2021-04-08 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dockers', '0014_auto_20210408_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 13, 46, 24, 432101, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 13, 46, 24, 432133, tzinfo=utc), verbose_name='date last update'),
        ),
    ]
